version: '3.4'

services:
  employee-time-tracker-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: employee-time-tracker-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1"]
      interval: 30s        # Wait 30 seconds between healthchecks
      timeout: 20s         # Give each check up to 20 seconds to succeed
      retries: 20          # Try up to 20 times before failing
      start_period: 120s   # Wait 2 minutes before starting healthchecks

  employee-time-tracker-api:
    image: employee-time-tracker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - employee-time-tracker-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=employee-time-tracker-db,1433;Database=EmployeeTimeTracker;User=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True;
